package com.runlify.metadata;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class FieldMetadataTest {

    // -----------------------------------------------------------------------
    // Category predicates
    // -----------------------------------------------------------------------

    @Test
    void isId_trueForIdCategory() {
        assertTrue(field("test", "string", "id").isId());
    }

    @Test
    void isId_falseForScalar() {
        assertFalse(field("test", "string", "scalar").isId());
    }

    @Test
    void isScalar_trueForScalarCategory() {
        assertTrue(field("test", "string", "scalar").isScalar());
    }

    @Test
    void isLink_trueForLinkCategory() {
        assertTrue(field("test", "string", "link").isLink());
    }

    @Test
    void isLink_falseForScalar() {
        assertFalse(field("test", "string", "scalar").isLink());
    }

    // -----------------------------------------------------------------------
    // Boolean accessors — null means false
    // -----------------------------------------------------------------------

    @Test
    void booleanAccessors_nullMeansFalse() {
        var f = field("test", "string", "scalar");
        assertAll(
            () -> assertFalse(f.isRequired()),
            () -> assertFalse(f.isRequiredOnInput()),
            () -> assertFalse(f.isUpdatable()),
            () -> assertFalse(f.isUpdatableByUser()),
            () -> assertFalse(f.isHidden()),
            () -> assertFalse(f.isSearchable()),
            () -> assertFalse(f.isAutoGenerated()),
            () -> assertFalse(f.isArray())
        );
    }

    @Test
    void isRequired_trueWhenSet() {
        var f = new FieldMetadata("n", "string", "scalar",
            true, null, null, null, null, null, null,
            null, null, null, null, null, null,
            null, null, null, null, null);
        assertTrue(f.isRequired());
    }

    @Test
    void isHidden_trueWhenSet() {
        var f = new FieldMetadata("n", "string", "scalar",
            null, null, null, null, true, null, null,
            null, null, null, null, null, null,
            null, null, null, null, null);
        assertTrue(f.isHidden());
    }

    @Test
    void isSearchable_trueWhenSet() {
        var f = new FieldMetadata("n", "string", "scalar",
            null, null, null, null, null, true, null,
            null, null, null, null, null, null,
            null, null, null, null, null);
        assertTrue(f.isSearchable());
    }

    @Test
    void isAutoGenerated_trueWhenSet() {
        var f = new FieldMetadata("id", "int", "id",
            null, null, null, null, null, null, null,
            true, "autoincrement()", null, null, null, null,
            null, null, null, null, null);
        assertTrue(f.isAutoGenerated());
    }

    // -----------------------------------------------------------------------
    // Type conversions — edge cases
    // -----------------------------------------------------------------------

    @Test
    void sqlType_unknownTypeThrows() {
        var f = field("test", "unknown", "scalar");
        var ex = assertThrows(IllegalArgumentException.class, f::sqlType);
        assertTrue(ex.getMessage().contains("unknown"));
    }

    @Test
    void graphqlType_unknownTypeThrows() {
        var f = field("test", "unknown", "scalar");
        var ex = assertThrows(IllegalArgumentException.class, f::graphqlType);
        assertTrue(ex.getMessage().contains("unknown"));
    }

    @Test
    void sqlType_bool() {
        assertEquals("BOOLEAN", field("n", "bool", "scalar").sqlType());
    }

    @Test
    void graphqlType_bool() {
        assertEquals("Boolean", field("n", "bool", "scalar").graphqlType());
    }

    @Test
    void sqlType_date() {
        assertEquals("DATE", field("n", "date", "scalar").sqlType());
    }

    @Test
    void graphqlType_dateAndDatetime_areStrings() {
        assertEquals("String", field("n", "date", "scalar").graphqlType());
        assertEquals("String", field("n", "datetime", "scalar").graphqlType());
    }

    // -----------------------------------------------------------------------
    // Filters default
    // -----------------------------------------------------------------------

    @Test
    void filters_defaultsToEmptyList() {
        var f = field("n", "string", "scalar");
        assertNotNull(f.filters());
        assertTrue(f.filters().isEmpty());
    }

    @Test
    void filters_preservedWhenProvided() {
        var f = new FieldMetadata("n", "string", "scalar",
            null, null, null, null, null, null, null,
            null, null, null, null, null, null,
            null, null, null, null, List.of("equal", "in"));
        assertEquals(List.of("equal", "in"), f.filters());
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static FieldMetadata field(String name, String type, String category) {
        return new FieldMetadata(name, type, category,
            null, null, null, null, null, null, null,
            null, null, null, null, null, null,
            null, null, null, null, null);
    }
}
