package com.runlify.metadata;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.*;

class MetadataDeserializationTest {

    private static final ObjectMapper mapper = new ObjectMapper()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    private static final String FIXTURES_BASE = "../tests/fixtures";

    private ProjectMetadata load(String fixture) throws Exception {
        var file = new File(FIXTURES_BASE + "/" + fixture + "/metadata.json");
        assertTrue(file.exists(), "Fixture not found: " + file.getAbsolutePath());
        return mapper.readValue(file, ProjectMetadata.class);
    }

    @Test
    void withAutoId_catalog() throws Exception {
        var meta = load("with-auto-id");
        assertEquals("test", meta.name());
        assertEquals("tst", meta.prefix());
        assertEquals(1, meta.catalogs().size());
        assertEquals(0, meta.documents().size());

        var items = meta.catalogs().get(0);
        assertEquals("items", items.name());
        assertEquals("catalog", items.type());

        // ID field is auto-increment int
        var idField = items.idField();
        assertEquals("int", idField.type());
        assertTrue(idField.isAutoGenerated());
        assertEquals("autoincrement()", idField.defaultDbValue());
    }

    @Test
    void withRelations_linkField() throws Exception {
        var meta = load("with-relations");
        assertEquals(2, meta.catalogs().size());

        var articles = meta.catalogs().stream()
            .filter(e -> "articles".equals(e.name()))
            .findFirst().orElseThrow();

        var linkField = articles.fields().stream()
            .filter(f -> "categoryId".equals(f.name()))
            .findFirst().orElseThrow();

        assertTrue(linkField.isLink());
        assertEquals("categories", linkField.linkEntity());
        assertTrue(linkField.filters().contains("in"));
        assertTrue(linkField.filters().contains("not_in"));
    }

    @Test
    void withDocumentRegistry_documentAndSumRegistry() throws Exception {
        var meta = load("with-document-registry");
        assertEquals(1, meta.documents().size());
        assertEquals(1, meta.sumRegistries().size());

        var invoice = meta.documents().get(0);
        assertEquals("invoices", invoice.name());
        assertTrue(invoice.isDocument());
        assertTrue(invoice.registries().contains("invoiceTotals"));

        var registry = meta.sumRegistries().get(0);
        assertEquals("invoiceTotals", registry.name());
        assertTrue(registry.isSumRegistry());
        assertTrue(registry.isRegistrarDepended());
        assertFalse(registry.dimensions().isEmpty());
        assertFalse(registry.resources().isEmpty());

        // ID field is auto-generated cuid
        var regId = registry.idField();
        assertTrue(regId.isAutoGenerated());
        assertEquals("cuid()", regId.defaultDbValue());
    }

    @Test
    void withInfoRegistry_periodicRegistry() throws Exception {
        var meta = load("with-info-registry");
        assertEquals(1, meta.infoRegistries().size());

        var prices = meta.infoRegistries().get(0);
        assertTrue(prices.isInfoRegistry());
        assertEquals("day", prices.period());
        assertFalse(prices.dimensions().isEmpty());
        assertFalse(prices.resources().isEmpty());
    }

    @Test
    void fieldSqlTypes() {
        assertEquals("TEXT", fieldWithType("string").sqlType());
        assertEquals("INTEGER", fieldWithType("int").sqlType());
        assertEquals("DOUBLE PRECISION", fieldWithType("float").sqlType());
        assertEquals("BOOLEAN", fieldWithType("bool").sqlType());
        assertEquals("TIMESTAMPTZ", fieldWithType("datetime").sqlType());
        assertEquals("DATE", fieldWithType("date").sqlType());
        assertEquals("BIGINT", fieldWithType("bigint").sqlType());
    }

    @Test
    void fieldGraphqlTypes() {
        assertEquals("String", fieldWithType("string").graphqlType());
        assertEquals("Int", fieldWithType("int").graphqlType());
        assertEquals("Float", fieldWithType("float").graphqlType());
        assertEquals("Boolean", fieldWithType("bool").graphqlType());
        assertEquals("String", fieldWithType("datetime").graphqlType());
        assertEquals("String", fieldWithType("date").graphqlType());
        assertEquals("String", fieldWithType("bigint").graphqlType());
    }

    @Test
    void allEntities_combinesAllTypes() throws Exception {
        var meta = load("with-document-registry");
        var all = meta.allEntities();
        assertEquals(meta.catalogs().size() + meta.documents().size()
            + meta.infoRegistries().size() + meta.sumRegistries().size(), all.size());
    }

    private FieldMetadata fieldWithType(String type) {
        return new FieldMetadata(
            "test", type, "scalar",
            null, null, null, null, null, null, null,
            null, null, null, null, null, null,
            null, null, null, null, null
        );
    }
}
