import fs from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import {
  type PreparedBackend,
  prepareBackend,
  runOrFail,
  teardownBackend,
} from './prepare-backend.js'

describe('e2e: auto-generated string id entity (with-auto-string-id)', () => {
  let prepared: PreparedBackend

  beforeAll(async () => {
    prepared = await prepareBackend('with-auto-string-id')
  }, 180000)

  afterAll(() => {
    teardownBackend({ prepared })
  })

  it('tsc --noEmit succeeds', () => {
    runOrFail('tsc', 'npx tsc --noEmit', {
      cwd: prepared.backDir,
      timeout: 30000,
    })
  })

  it('prisma validate succeeds', () => {
    runOrFail('prisma validate', 'npx prisma validate', {
      cwd: prepared.backDir,
      timeout: 15000,
      env: { ...process.env, DATABASE_MAIN_WRITE_URI: 'postgresql://localhost:5432/test' },
    })
  })

  it('Prisma schema has Ticket model with String cuid() id', () => {
    const schema = fs.readFileSync(path.join(prepared.backDir, 'prisma/schema.prisma'), 'utf-8')
    expect(schema).toContain('model Ticket {')
    expect(schema).toMatch(/id\s+String/)
    expect(schema).toContain('@id')
    expect(schema).toContain('@default(cuid())')
  })

  it('Prisma schema has correct field types', () => {
    const schema = fs.readFileSync(path.join(prepared.backDir, 'prisma/schema.prisma'), 'utf-8')
    expect(schema).toMatch(/subject\s+String/)
  })

  it('GraphQL typeDefs use ID for string id', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/tickets/baseTypeDefs.ts'),
      'utf-8',
    )
    expect(typeDefs).toContain('type Ticket {')
    expect(typeDefs).toContain('id: ID!')
    expect(typeDefs).toContain('subject: String!')
  })

  it('typeDefs do not require id on create mutation (auto-generated cuid)', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/tickets/baseTypeDefs.ts'),
      'utf-8',
    )
    const createMatch = typeDefs.match(/createTicket\(([^)]+)\)/s)
    expect(createMatch).toBeTruthy()
    const createArgs = createMatch?.[1]
    expect(createArgs).not.toMatch(/\bid\s*:/)
  })

  it('serviceConfig has autogeneratedStringId true', () => {
    const configPath = path.join(prepared.backDir, 'src/adm/services/TicketsService/config.ts')
    const config = fs.readFileSync(configPath, 'utf-8')
    // autogeneratedStringId should be TRUE (string + autoGenerated)
    expect(config).toContain('autogeneratedStringId')
    expect(config).toMatch(/autogeneratedStringId.*true/)
  })
})
