import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { type CrudClient, createCrudClient } from './graphql-client.js'
import { type SetupServerResult, setupServer, teardownServer } from './prepare-backend.js'

interface Ticket {
  id: string
  subject: string
}

describe('e2e: GraphQL API for auto-generated string id entity (cuid)', () => {
  let ctx: SetupServerResult
  let tickets: CrudClient<Ticket>

  beforeAll(async () => {
    ctx = await setupServer('with-auto-string-id', 'test_auto_string_api')
    tickets = createCrudClient<Ticket>(
      ctx.server,
      'Ticket',
      'id subject',
    )
  }, 240000)

  afterAll(async () => {
    await teardownServer(ctx)
  })

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  async function createOk(data: Record<string, unknown>): Promise<Ticket> {
    const r = await tickets.create(data)
    expect(r.errors).toBeUndefined()
    return r.data!.createTicket!
  }

  async function removeQuiet(id: string): Promise<void> {
    await tickets.remove(id)
  }

  // ---------------------------------------------------------------------------
  // 1. Auto-generated string (cuid) id
  // ---------------------------------------------------------------------------

  describe('auto-generated string id (cuid)', () => {
    it('creates ticket without providing id — server generates cuid', async () => {
      const ticket = await createOk({ subject: 'Bug report' })

      expect(ticket.id).toBeTypeOf('string')
      expect(ticket.id.length).toBeGreaterThan(0)
      expect(ticket.subject).toBe('Bug report')

      await removeQuiet(ticket.id)
    })

    it('creates two tickets — ids are distinct cuid strings', async () => {
      const a = await createOk({ subject: 'Issue A' })
      const b = await createOk({ subject: 'Issue B' })

      expect(a.id).not.toBe(b.id)
      expect(a.id).toBeTypeOf('string')
      expect(b.id).toBeTypeOf('string')

      await removeQuiet(a.id)
      await removeQuiet(b.id)
    })

    it('generated id is a non-empty string (server-generated)', async () => {
      const ticket = await createOk({ subject: 'Id format check' })

      // autogeneratedStringId uses uuidv4() at runtime (Prisma default is cuid() but
      // the BaseService generates the id before Prisma insert)
      expect(ticket.id).toBeTypeOf('string')
      expect(ticket.id.length).toBeGreaterThan(10)

      await removeQuiet(ticket.id)
    })

    it('reads ticket by generated string id', async () => {
      const created = await createOk({ subject: 'ReadMe' })

      const r = await tickets.findOne(created.id)
      expect(r.errors).toBeUndefined()
      expect(r.data?.Ticket?.subject).toBe('ReadMe')

      await removeQuiet(created.id)
    })

    it('updates ticket by generated string id', async () => {
      const created = await createOk({ subject: 'Old subject' })

      const r = await tickets.update({ id: created.id, subject: 'New subject' })
      expect(r.errors).toBeUndefined()
      expect(r.data?.updateTicket?.subject).toBe('New subject')

      await removeQuiet(created.id)
    })

    it('removes ticket by generated string id', async () => {
      const created = await createOk({ subject: 'Gone' })

      const r = await tickets.remove(created.id)
      expect(r.errors).toBeUndefined()

      const check = await tickets.findOne(created.id)
      expect(check.data!.Ticket).toBeNull()
    })
  })

  // ---------------------------------------------------------------------------
  // 2. Difference from manual string id
  // ---------------------------------------------------------------------------

  describe('auto vs manual string id', () => {
    it('create does not require id field (unlike manual string id)', async () => {
      // This should succeed without providing 'id'
      const ticket = await createOk({ subject: 'No id provided' })
      expect(ticket.id).toBeTruthy()
      await removeQuiet(ticket.id)
    })
  })

  // ---------------------------------------------------------------------------
  // 3. findAll, sorting, count
  // ---------------------------------------------------------------------------

  describe('findAll and sorting', () => {
    it('lists all tickets', async () => {
      const a = await createOk({ subject: 'Alpha' })
      const b = await createOk({ subject: 'Beta' })

      const r = await tickets.findAll()
      expect(r.errors).toBeUndefined()
      const subjects = r.data?.allTickets?.map((t: Ticket) => t.subject) ?? []
      expect(subjects).toContain('Alpha')
      expect(subjects).toContain('Beta')

      await removeQuiet(a.id)
      await removeQuiet(b.id)
    })

    it('counts tickets', async () => {
      const a = await createOk({ subject: 'C1' })
      const b = await createOk({ subject: 'C2' })

      const r = await tickets.count()
      expect(r.errors).toBeUndefined()
      expect(r.data?._allTicketsMeta?.count).toBeGreaterThanOrEqual(2)

      await removeQuiet(a.id)
      await removeQuiet(b.id)
    })
  })
})
