import fs from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import {
  type PreparedBackend,
  prepareBackend,
  runOrFail,
  teardownBackend,
} from './prepare-backend.js'

describe('e2e: auto-generated bigint id entity (with-bigint-id)', () => {
  let prepared: PreparedBackend

  beforeAll(async () => {
    prepared = await prepareBackend('with-bigint-id')
  }, 180000)

  afterAll(() => {
    teardownBackend({ prepared })
  })

  it('tsc --noEmit succeeds', () => {
    runOrFail('tsc', 'npx tsc --noEmit', {
      cwd: prepared.backDir,
      timeout: 30000,
    })
  })

  it('prisma validate succeeds', () => {
    runOrFail('prisma validate', 'npx prisma validate', {
      cwd: prepared.backDir,
      timeout: 15000,
      env: { ...process.env, DATABASE_MAIN_WRITE_URI: 'postgresql://localhost:5432/test' },
    })
  })

  it('Prisma schema has Counter model with BigInt autoincrement id', () => {
    const schema = fs.readFileSync(path.join(prepared.backDir, 'prisma/schema.prisma'), 'utf-8')
    expect(schema).toContain('model Counter {')
    expect(schema).toMatch(/id\s+BigInt/)
    expect(schema).toContain('@id')
    expect(schema).toContain('@default(autoincrement())')
  })

  it('Prisma schema has correct field types', () => {
    const schema = fs.readFileSync(path.join(prepared.backDir, 'prisma/schema.prisma'), 'utf-8')
    expect(schema).toMatch(/label\s+String/)
  })

  it('GraphQL typeDefs use BigInt for id', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/counters/baseTypeDefs.ts'),
      'utf-8',
    )
    expect(typeDefs).toContain('type Counter {')
    expect(typeDefs).toContain('id: BigInt!')
    expect(typeDefs).toContain('label: String!')
  })

  it('typeDefs do not require id on create mutation (auto-generated)', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/counters/baseTypeDefs.ts'),
      'utf-8',
    )
    const createMatch = typeDefs.match(/createCounter\(([^)]+)\)/s)
    expect(createMatch).toBeTruthy()
    const createArgs = createMatch![1]
    expect(createArgs).not.toMatch(/\bid\s*:\s*BigInt!/)
  })

  it('serviceConfig has autoGenerated / non-string-auto flags', () => {
    const configPath = path.join(prepared.backDir, 'src/adm/services/CountersService/config.ts')
    const config = fs.readFileSync(configPath, 'utf-8')
    // autogeneratedStringId should be false (bigint, not string)
    expect(config).toContain('autogeneratedStringId')
    expect(config).toMatch(/autogeneratedStringId.*false/)
  })
})
