import fs from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import {
  type PreparedBackend,
  prepareBackend,
  runOrFail,
  teardownBackend,
} from './prepare-backend.js'

describe('e2e: manual int id entity (with-manual-int-id)', () => {
  let prepared: PreparedBackend

  beforeAll(async () => {
    prepared = await prepareBackend('with-manual-int-id')
  }, 180000)

  afterAll(() => {
    teardownBackend({ prepared })
  })

  it('tsc --noEmit succeeds', () => {
    runOrFail('tsc', 'npx tsc --noEmit', {
      cwd: prepared.backDir,
      timeout: 30000,
    })
  })

  it('prisma validate succeeds', () => {
    runOrFail('prisma validate', 'npx prisma validate', {
      cwd: prepared.backDir,
      timeout: 15000,
      env: { ...process.env, DATABASE_MAIN_WRITE_URI: 'postgresql://localhost:5432/test' },
    })
  })

  it('Prisma schema has Entry model with int id (no autoincrement)', () => {
    const schema = fs.readFileSync(path.join(prepared.backDir, 'prisma/schema.prisma'), 'utf-8')
    expect(schema).toContain('model Entry {')
    expect(schema).toMatch(/id\s+Int/)
    expect(schema).toContain('@id')
    // manual id — no autoincrement
    expect(schema).not.toContain('@default(autoincrement())')
  })

  it('Prisma schema has correct field types', () => {
    const schema = fs.readFileSync(path.join(prepared.backDir, 'prisma/schema.prisma'), 'utf-8')
    expect(schema).toMatch(/label\s+String/)
  })

  it('GraphQL typeDefs use Int for id and require id on create', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/entries/baseTypeDefs.ts'),
      'utf-8',
    )
    expect(typeDefs).toContain('type Entry {')
    expect(typeDefs).toContain('id: Int!')
    expect(typeDefs).toContain('label: String!')
  })

  it('typeDefs require id on create mutation (user-provided)', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/entries/baseTypeDefs.ts'),
      'utf-8',
    )
    const createMatch = typeDefs.match(/createEntry\(([^)]+)\)/s)
    expect(createMatch).toBeTruthy()
    const createArgs = createMatch?.[1]
    expect(createArgs).toMatch(/\bid\s*:\s*Int!/)
  })

  it('typeDefs define correct Entry type fields', () => {
    const typeDefs = fs.readFileSync(
      path.join(prepared.backDir, 'src/adm/graph/services/entries/baseTypeDefs.ts'),
      'utf-8',
    )
    expect(typeDefs).toContain('id: Int!')
    expect(typeDefs).toContain('label: String!')
  })

  it('serviceConfig has autoGenerated false for id', () => {
    const configPath = path.join(prepared.backDir, 'src/adm/services/EntriesService/config.ts')
    const config = fs.readFileSync(configPath, 'utf-8')
    // autogeneratedStringId should be false (it's int, not string)
    expect(config).toContain('autogeneratedStringId')
    expect(config).toMatch(/autogeneratedStringId.*false/)
  })
})
