package com.runlify.graphql;

import com.runlify.metadata.EntityMetadata;
import com.runlify.metadata.EntityNames;
import graphql.schema.DataFetcher;
import graphql.schema.DataFetchingEnvironment;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Creates graphql-java {@link DataFetcher} instances for standard CRUD
 * operations, driven by entity metadata. All SQL is built dynamically.
 */
@Component
public class CrudDataFetcherFactory {

    private final JdbcTemplate jdbc;

    public CrudDataFetcherFactory(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    // -----------------------------------------------------------------------
    // findOne: Entity(id: ...)
    // -----------------------------------------------------------------------

    public DataFetcher<Map<String, Object>> findOne(EntityMetadata entity) {
        var table = EntityNames.tableName(entity);
        return env -> {
            var id = env.getArgument("id");
            var sql = "SELECT * FROM \"%s\" WHERE \"id\" = ? LIMIT 1".formatted(table);
            var rows = jdbc.queryForList(sql, id);
            return rows.isEmpty() ? null : rows.get(0);
        };
    }

    // -----------------------------------------------------------------------
    // findAll: allEntities(page, perPage, sortField, sortOrder, filter)
    // -----------------------------------------------------------------------

    public DataFetcher<List<Map<String, Object>>> findAll(EntityMetadata entity) {
        var table = EntityNames.tableName(entity);
        return env -> {
            var where = buildWhereClause(entity, env);
            var sql = new StringBuilder("SELECT * FROM \"%s\"".formatted(table));
            if (!where.conditions().isEmpty()) {
                sql.append(" WHERE ").append(String.join(" AND ", where.conditions()));
            }

            // Sorting
            var sortField = env.<String>getArgument("sortField");
            var sortOrder = env.<String>getArgument("sortOrder");
            if (sortField != null) {
                var order = "DESC".equalsIgnoreCase(sortOrder) ? "DESC" : "ASC";
                sql.append(" ORDER BY \"%s\" %s".formatted(sortField, order));
            } else if (entity.sortField() != null) {
                var order = entity.sortOrder() != null ? entity.sortOrder() : "ASC";
                sql.append(" ORDER BY \"%s\" %s".formatted(entity.sortField(), order));
            }

            // Pagination
            var page = env.<Integer>getArgument("page");
            var perPage = env.<Integer>getArgument("perPage");
            if (perPage != null) {
                sql.append(" LIMIT %d".formatted(perPage));
                if (page != null && page > 0) {
                    sql.append(" OFFSET %d".formatted(page * perPage));
                }
            }

            return jdbc.queryForList(sql.toString(), where.params().toArray());
        };
    }

    // -----------------------------------------------------------------------
    // count: _allEntitiesMeta(filter)
    // -----------------------------------------------------------------------

    public DataFetcher<Map<String, Object>> count(EntityMetadata entity) {
        var table = EntityNames.tableName(entity);
        return env -> {
            var where = buildWhereClause(entity, env);
            var sql = new StringBuilder("SELECT COUNT(*) as count FROM \"%s\"".formatted(table));
            if (!where.conditions().isEmpty()) {
                sql.append(" WHERE ").append(String.join(" AND ", where.conditions()));
            }
            var count = jdbc.queryForObject(sql.toString(), Long.class, where.params().toArray());
            return Map.of("count", count != null ? count : 0L);
        };
    }

    // -----------------------------------------------------------------------
    // create: createEntity(field1: val1, ...)
    // -----------------------------------------------------------------------

    public DataFetcher<Map<String, Object>> create(EntityMetadata entity) {
        var table = EntityNames.tableName(entity);
        return env -> {
            var args = collectArgs(entity, env, false);

            // Auto-generate cuid for string id if needed
            var idField = entity.idField();
            if (idField.isAutoGenerated() && "cuid()".equals(idField.defaultDbValue())
                && !args.containsKey("id")) {
                args.put("id", generateCuid());
            }

            // Auto-populate search field
            populateSearch(entity, args);

            // Apply default backend value expressions for missing fields
            applyDefaults(entity, args);

            if (args.isEmpty()) {
                throw new IllegalArgumentException("No fields provided for create");
            }

            var columns = args.keySet().stream()
                .map(c -> "\"%s\"".formatted(c))
                .collect(Collectors.joining(", "));
            var placeholders = args.keySet().stream()
                .map(c -> "?")
                .collect(Collectors.joining(", "));
            var sql = "INSERT INTO \"%s\" (%s) VALUES (%s) RETURNING *"
                .formatted(table, columns, placeholders);

            return jdbc.queryForMap(sql, args.values().toArray());
        };
    }

    // -----------------------------------------------------------------------
    // update: updateEntity(id: ..., field1: newVal, ...)
    // -----------------------------------------------------------------------

    public DataFetcher<Map<String, Object>> update(EntityMetadata entity) {
        var table = EntityNames.tableName(entity);
        return env -> {
            var id = env.getArgument("id");
            var args = collectArgs(entity, env, true);

            // Re-populate search if any searchable field was updated
            if (hasSearchableField(entity, args.keySet())) {
                // Need to merge with existing data for full search text
                var existing = jdbc.queryForMap(
                    "SELECT * FROM \"%s\" WHERE \"id\" = ?".formatted(table), id);
                existing.putAll(args);
                populateSearch(entity, existing);
                args.put("search", existing.get("search"));
            }

            if (args.isEmpty()) {
                // Nothing to update, just return the existing row
                return jdbc.queryForMap(
                    "SELECT * FROM \"%s\" WHERE \"id\" = ?".formatted(table), id);
            }

            var setClauses = args.keySet().stream()
                .map(c -> "\"%s\" = ?".formatted(c))
                .collect(Collectors.joining(", "));
            var params = new ArrayList<>(args.values());
            params.add(id);
            var sql = "UPDATE \"%s\" SET %s WHERE \"id\" = ? RETURNING *"
                .formatted(table, setClauses);

            return jdbc.queryForMap(sql, params.toArray());
        };
    }

    // -----------------------------------------------------------------------
    // remove: removeEntity(id: ...)
    // -----------------------------------------------------------------------

    public DataFetcher<Map<String, Object>> remove(EntityMetadata entity) {
        var table = EntityNames.tableName(entity);
        var singular = EntityNames.singularName(entity);
        return env -> {
            var id = env.getArgument("id");
            var sql = "DELETE FROM \"%s\" WHERE \"id\" = ? RETURNING *".formatted(table);
            var rows = jdbc.queryForList(sql, id);
            if (rows.isEmpty()) {
                throw new RuntimeException("%s not found: %s".formatted(singular, id));
            }
            return rows.get(0);
        };
    }

    // -----------------------------------------------------------------------
    // Where clause builder (from filter argument)
    // -----------------------------------------------------------------------

    private record WhereClause(List<String> conditions, List<Object> params) {}

    private WhereClause buildWhereClause(EntityMetadata entity, DataFetchingEnvironment env) {
        var conditions = new ArrayList<String>();
        var params = new ArrayList<Object>();

        @SuppressWarnings("unchecked")
        var filter = (Map<String, Object>) env.getArgument("filter");
        if (filter == null) return new WhereClause(conditions, params);

        for (var entry : filter.entrySet()) {
            var key = entry.getKey();
            var value = entry.getValue();
            if (value == null) continue;

            if ("q".equals(key)) {
                conditions.add("\"search\" ILIKE ?");
                params.add("%" + value + "%");
                continue;
            }

            if ("ids".equals(key)) {
                @SuppressWarnings("unchecked")
                var ids = (List<Object>) value;
                if (!ids.isEmpty()) {
                    var placeholders = ids.stream().map(i -> "?").collect(Collectors.joining(", "));
                    conditions.add("\"id\" IN (%s)".formatted(placeholders));
                    params.addAll(ids);
                }
                continue;
            }

            // Suffix-based filters
            if (key.endsWith("_lte")) {
                var col = key.substring(0, key.length() - 4);
                conditions.add("\"%s\" <= ?".formatted(col));
                params.add(value);
            } else if (key.endsWith("_gte")) {
                var col = key.substring(0, key.length() - 4);
                conditions.add("\"%s\" >= ?".formatted(col));
                params.add(value);
            } else if (key.endsWith("_lt")) {
                var col = key.substring(0, key.length() - 3);
                conditions.add("\"%s\" < ?".formatted(col));
                params.add(value);
            } else if (key.endsWith("_gt")) {
                var col = key.substring(0, key.length() - 3);
                conditions.add("\"%s\" > ?".formatted(col));
                params.add(value);
            } else if (key.endsWith("_in")) {
                var col = key.substring(0, key.length() - 3);
                @SuppressWarnings("unchecked")
                var list = (List<Object>) value;
                if (!list.isEmpty()) {
                    var placeholders = list.stream().map(i -> "?").collect(Collectors.joining(", "));
                    conditions.add("\"%s\" IN (%s)".formatted(col, placeholders));
                    params.addAll(list);
                }
            } else if (key.endsWith("_not_in")) {
                var col = key.substring(0, key.length() - 7);
                @SuppressWarnings("unchecked")
                var list = (List<Object>) value;
                if (!list.isEmpty()) {
                    var placeholders = list.stream().map(i -> "?").collect(Collectors.joining(", "));
                    conditions.add("\"%s\" NOT IN (%s)".formatted(col, placeholders));
                    params.addAll(list);
                }
            } else if (key.endsWith("_defined")) {
                var col = key.substring(0, key.length() - 8);
                if (Boolean.TRUE.equals(value)) {
                    conditions.add("\"%s\" IS NOT NULL".formatted(col));
                } else {
                    conditions.add("\"%s\" IS NULL".formatted(col));
                }
            } else {
                // Equal filter
                conditions.add("\"%s\" = ?".formatted(key));
                params.add(value);
            }
        }

        return new WhereClause(conditions, params);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Collect non-null arguments from the GraphQL environment, skipping id on update. */
    private LinkedHashMap<String, Object> collectArgs(
        EntityMetadata entity, DataFetchingEnvironment env, boolean isUpdate
    ) {
        var args = new LinkedHashMap<String, Object>();
        for (var field : entity.fields()) {
            if (field.isHidden()) continue;
            if (isUpdate && field.isId()) continue;
            if (env.containsArgument(field.name())) {
                var value = env.getArgument(field.name());
                if (value != null) {
                    args.put(field.name(), value);
                }
            }
        }
        return args;
    }

    /** Build the search field value from all searchable fields. */
    private void populateSearch(EntityMetadata entity, Map<String, Object> data) {
        var searchParts = new ArrayList<String>();
        for (var field : entity.fields()) {
            if (field.isSearchable() && data.containsKey(field.name())) {
                var val = data.get(field.name());
                if (val != null) {
                    searchParts.add(val.toString());
                }
            }
        }
        data.put("search", String.join(" ", searchParts));
    }

    /** Check if any of the updated fields are searchable. */
    private boolean hasSearchableField(EntityMetadata entity, Set<String> updatedFields) {
        return entity.fields().stream()
            .anyMatch(f -> f.isSearchable() && updatedFields.contains(f.name()));
    }

    /** Apply default backend value expressions for missing fields. */
    private void applyDefaults(EntityMetadata entity, Map<String, Object> args) {
        for (var field : entity.fields()) {
            if (args.containsKey(field.name())) continue;
            if (field.isId()) continue;
            var expr = field.defaultBackendValueExpression();
            if (expr != null && !expr.isEmpty()) {
                // Simple literal parsing
                if (expr.startsWith("'") && expr.endsWith("'")) {
                    args.put(field.name(), expr.substring(1, expr.length() - 1));
                } else {
                    try {
                        args.put(field.name(), Integer.parseInt(expr));
                    } catch (NumberFormatException e) {
                        try {
                            args.put(field.name(), Double.parseDouble(expr));
                        } catch (NumberFormatException e2) {
                            args.put(field.name(), expr);
                        }
                    }
                }
            }
        }
    }

    /** Generate a CUID-like unique identifier. */
    static String generateCuid() {
        // Simple CUID-compatible unique id: timestamp + random
        var timestamp = Long.toString(System.currentTimeMillis(), 36);
        var random = Long.toString((long) (Math.random() * 1_000_000_000L), 36);
        return "c" + timestamp + random;
    }
}
