package com.runlify.metadata;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/**
 * Describes a single field within an entity.
 * Used for entity fields, dimensions, and resources (same shape).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record FieldMetadata(
    String name,
    String type,
    String category,

    // Constraints
    Boolean required,
    Boolean requiredOnInput,
    Boolean updatable,
    Boolean updatableByUser,
    Boolean hidden,
    Boolean searchable,
    Boolean array,

    // ID-specific
    Boolean autoGenerated,
    String defaultDbValue,

    // Default values
    String defaultBackendValueExpression,
    String defaultValueExpression,

    // Type-specific
    String stringType,
    String numberType,

    // Link-specific
    String linkEntity,
    String externalEntity,
    String linkCategory,
    String predefinedLinkedEntity,

    // Filters
    List<String> filters
) {
    public FieldMetadata {
        filters = filters != null ? filters : List.of();
    }

    public boolean isId()     { return "id".equals(category); }
    public boolean isScalar() { return "scalar".equals(category); }
    public boolean isLink()   { return "link".equals(category); }

    public boolean isRequired()        { return Boolean.TRUE.equals(required); }
    public boolean isRequiredOnInput() { return Boolean.TRUE.equals(requiredOnInput); }
    public boolean isUpdatable()       { return Boolean.TRUE.equals(updatable); }
    public boolean isUpdatableByUser() { return Boolean.TRUE.equals(updatableByUser); }
    public boolean isHidden()          { return Boolean.TRUE.equals(hidden); }
    public boolean isSearchable()      { return Boolean.TRUE.equals(searchable); }
    public boolean isAutoGenerated()   { return Boolean.TRUE.equals(autoGenerated); }
    public boolean isArray()           { return Boolean.TRUE.equals(array); }

    /** SQL column type for this field. */
    public String sqlType() {
        return switch (type) {
            case "string"   -> "TEXT";
            case "int"      -> "INTEGER";
            case "float"    -> "DOUBLE PRECISION";
            case "bool"     -> "BOOLEAN";
            case "datetime" -> "TIMESTAMPTZ";
            case "date"     -> "DATE";
            case "bigint"   -> "BIGINT";
            default -> throw new IllegalArgumentException("Unknown field type: " + type);
        };
    }

    /** GraphQL scalar type for this field. */
    public String graphqlType() {
        return switch (type) {
            case "string"   -> "String";
            case "int"      -> "Int";
            case "float"    -> "Float";
            case "bool"     -> "Boolean";
            case "datetime" -> "String";
            case "date"     -> "String";
            case "bigint"   -> "String";
            default -> throw new IllegalArgumentException("Unknown field type: " + type);
        };
    }
}
