/* Stub: services types */

import type { PrismaClient } from '@prisma/client'
import type { AdditionalServices } from './AdditionalServices'
import type { BaseServices } from './BaseServices'
import type Entity from '../../types/Entity'

export type Services = BaseServices & AdditionalServices

export interface Context {
  prisma: PrismaClient
  service: <N extends keyof Services>(name: N) => Services[N]
  log: Record<string, (...args: unknown[]) => void>
  close: () => Promise<void>
  [key: string]: unknown
}

export interface ServiceConfig {
  idType: 'string' | 'bigint' | 'int'
  autogeneratedStringId: boolean
  auditable: boolean
  entityTypeId: Entity
  withSearch: boolean
  externalSearch: boolean
  sharded: boolean
  dateFields: string[]
  otherFields: string[]
  forbiddenForUserFields: string[]
  clearDBAfter?: { count: number; unit: 'year' | 'month' | 'day' | 'hour' | 'minute' }[]
  auditableOnlyByUser?: boolean
}

export interface DocumentConfig extends ServiceConfig {
  registries: string[]
  registrarDependedRegistries: string[]
  externalSearchDeps?: Partial<Record<string, string>>
}

export type BaseServiceConstrictors = {
  [K in keyof BaseServices]: (ctx: Context) => BaseServices[K]
}

export type AdditionalServiceConstrictors = {
  [K in keyof AdditionalServices]: (ctx: Context) => AdditionalServices[K]
}

export type IntegrationClientsConstrictors = Record<string, (ctx: Context) => unknown>

export type ServiceConstrictors = BaseServiceConstrictors &
  AdditionalServiceConstrictors &
  IntegrationClientsConstrictors
